/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import edu.tum.cs.cadmos.common.ListUtils;
import edu.tum.cs.cadmos.language.cadmos.Component;
import edu.tum.cs.cadmos.language.cadmos.Embedding;
import edu.tum.cs.cadmos.language.cadmos.Port;
import edu.tum.cs.cadmos.language.cadmos.PortRef;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class CadmosScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_PortRef_port(PortRef portRef, EReference ref) {
		final Embedding embedding = portRef.getEmbedding();
		final Component component;
		if (embedding == null) {
			component = EcoreUtil2.getContainerOfType(portRef, Component.class);
		} else {
			component = embedding.getComponent();
		}
		if (component == null) {
			return IScope.NULLSCOPE;
		}
		final List<Port> ports = ListUtils.filter(component.getElements(),
				Port.class);
		return Scopes.scopeFor(ports);
	}

}
