/*
* generated by Xtext
*/
package edu.tum.cs.cadmos.language.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CadmosOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
