/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

import edu.tum.cs.cadmos.language.scoping.CadmosXbaseBatchScopeProvider;
import edu.tum.cs.cadmos.language.scoping.CadmosXbaseScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class CadmosRuntimeModule extends
		edu.tum.cs.cadmos.language.AbstractCadmosRuntimeModule {

	@Override
	public Class<? extends XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
		/* Important for linking. */
		return CadmosXbaseBatchScopeProvider.class;
	}

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		/* Important for completion proposals. */
		return CadmosXbaseScopeProvider.class;
	}

}
