/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CadmosUiModule extends edu.tum.cs.cadmos.language.ui.AbstractCadmosUiModule {
	public CadmosUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
