/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language.ui.contentassist

import edu.tum.cs.cadmos.language.ui.contentassist.AbstractCadmosProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CadmosProposalProvider extends AbstractCadmosProposalProvider {
}
