/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CadmosRuntimeModule extends edu.tum.cs.cadmos.language.AbstractCadmosRuntimeModule {

}
