/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language.validation

import org.eclipse.xtext.validation.Check
import edu.tum.cs.cadmos.language.cadmos.Mapping
import edu.tum.cs.cadmos.language.cadmos.Role
import edu.tum.cs.cadmos.language.cadmos.CadmosPackage

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class CadmosValidator extends AbstractCadmosValidator {

	@Check
	def checkMappingsStartWithSoftwareComonent(Mapping m) {
		if (m.component != null && m.component.role != Role.SOFTWARE) {
			error('Mapped component must be a software component', CadmosPackage.Literals.MAPPING__COMPONENT)
		}
	}
/*
 * 
 */
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
