/*
 * generated by Xtext
 */
package edu.tum.cs.cadmos.language.validation

import org.eclipse.xtext.common.types.JvmTypeReference
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class CadmosValidator extends AbstractCadmosValidator { //  public static val INVALID_NAME = 'invalidName'
	//	@Check
	//	def checkGreetingStartsWithCapital(Greeting greeting) {
	//		if (!Character::isUpperCase(greeting.name.charAt(0))) {
	//			warning('Name should start with a capital', 
	//					MyDslPackage$Literals::GREETING__NAME,
	//					INVALID_NAME)
	//		}
	//	}
	//	@Check
	//	override checkTypeParameterNotUsedInStaticContext(JvmTypeReference ref) {
	//		// FIXME: Need to disable this check temporarily due to bug in XbaseJavaValidator (2.4.0) 
	//	}
}
